spring.application.name=paperNote
spring.messages.encoding=UTF-8

#SQL Init
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8


#message
spring.messages.basename=i18n/messages,i18n/ValidationMessages

#ポート
server.port=${PORT:8080}

#データソース
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:app_db}
spring.datasource.username=${PGUSER:appuser}
spring.datasource.password=${PGPASSWORD:appuser}

# MyBatis
mybatis.mapper-locations=classpath*:/mapper/postgres/*.xml
mybatis.configuration.map-underscore-to-camel-case=true


#Log Level
logging.level.com.example=debug